site_name:        FLOWUnsteady
repo_url:         http://github.com/byuflowlab/FLOWUnsteady
site_description: Aerodynamic Analysis Suite
site_author:      juddmehr

theme:
  name: cinder

extra_css:
  - assets/documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - documenter.js
  - search.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition
  - attr_list

docs_dir: 'build'